name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! Thanks for opening your first issue here! Please follow the issue template to help us help you!"
        pr-message: "Hello! Thanks for opening your first PR here! Please follow the PR template to help us help you!"